// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XCONTROLLER_H
#define XCONTROLLER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xcontroller_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XController_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XController;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XController_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XController_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XController_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XController_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XController_Initialize(XController *InstancePtr, u16 DeviceId);
XController_Config* XController_LookupConfig(u16 DeviceId);
int XController_CfgInitialize(XController *InstancePtr, XController_Config *ConfigPtr);
#else
int XController_Initialize(XController *InstancePtr, const char* InstanceName);
int XController_Release(XController *InstancePtr);
#endif


void XController_Set_config_V(XController *InstancePtr, u32 Data);
u32 XController_Get_config_V(XController *InstancePtr);
void XController_Set_packet2controller_V(XController *InstancePtr, u32 Data);
u32 XController_Get_packet2controller_V(XController *InstancePtr);
u32 XController_Get_controller2host_ack(XController *InstancePtr);
u32 XController_Get_controller2host_ack_vld(XController *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
