// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcontroller.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XController_CfgInitialize(XController *InstancePtr, XController_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XController_Set_config_V(XController *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XController_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTROLLER_AXILITES_ADDR_CONFIG_V_DATA, Data);
}

u32 XController_Get_config_V(XController *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XController_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTROLLER_AXILITES_ADDR_CONFIG_V_DATA);
    return Data;
}

void XController_Set_packet2controller_V(XController *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XController_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTROLLER_AXILITES_ADDR_PACKET2CONTROLLER_V_DATA, Data);
}

u32 XController_Get_packet2controller_V(XController *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XController_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTROLLER_AXILITES_ADDR_PACKET2CONTROLLER_V_DATA);
    return Data;
}

u32 XController_Get_controller2host_ack(XController *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XController_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTROLLER_AXILITES_ADDR_CONTROLLER2HOST_ACK_DATA);
    return Data;
}

u32 XController_Get_controller2host_ack_vld(XController *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XController_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTROLLER_AXILITES_ADDR_CONTROLLER2HOST_ACK_CTRL);
    return Data & 0x1;
}

